server:
  port: 8761

eureka: 
  client:
     fetch-registry: true
     register-with-eureka: true
     service-url:
       default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost

spring:
  cloud:
    gateway:
      locator:
        enabled: true
      routes:
        - id: service-user
           uri: lb://service-user
           predicates:
            - Path=/user/**
        - id: service-product
           uri: lb://service-product
           predicates:
            - Path=/product/**