server:
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
          default-label: gateway
          uri: https://github.com/jorgegc2187/microservicios
          search-paths: config-data
  application:
    name: config-server
            
